//! Specctra DSN / SES format keywords and tokens.

/// Lexical keyword in the Specctra DSN grammar.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Keyword {
    OpenParen,
    CloseParen,
    Pcb,
    Parser,
    Resolution,
    Unit,
    Structure,
    Layer,
    Boundary,
    Keepout,
    PlaceKeepout,
    Via,
    Rule,
    Width,
    Clearance,
    ClearanceClass,
    LayerRule,
    Placement,
    Component,
    Place,
    Library,
    Image,
    Pin,
    Padstack,
    Shape,
    Circle,
    Rectangle,
    Polygon,
    Path,
    Network,
    Net,
    Pins,
    Class,
    Classes,
    Wiring,
    Wire,
    ViaRule,
    Session,
    Routes,
    ResolutionScope,
    Plane,
    Autoroute,
    Fanout,
    Postroute,
    HostCad,
    HostVersion,
    SupplyPin,
    ConductionArea,
    Circuit,
}

impl Keyword {
    /// Matches a string token to a keyword (case-insensitive).
    pub fn parse(s: &str) -> Option<Keyword> {
        let lower = s.to_ascii_lowercase();
        match lower.as_str() {
            "circuit" => Some(Keyword::Circuit),
            "(" => Some(Keyword::OpenParen),
            ")" => Some(Keyword::CloseParen),
            "pcb" => Some(Keyword::Pcb),
            "parser" => Some(Keyword::Parser),
            "resolution" => Some(Keyword::Resolution),
            "unit" => Some(Keyword::Unit),
            "structure" => Some(Keyword::Structure),
            "layer" => Some(Keyword::Layer),
            "boundary" => Some(Keyword::Boundary),
            "keepout" => Some(Keyword::Keepout),
            "place_keepout" => Some(Keyword::PlaceKeepout),
            "via" => Some(Keyword::Via),
            "rule" => Some(Keyword::Rule),
            "width" => Some(Keyword::Width),
            "clearance" | "clear" => Some(Keyword::Clearance),
            "clearance_class" | "clearanceclass" => Some(Keyword::ClearanceClass),
            "layer_rule" => Some(Keyword::LayerRule),
            "placement" => Some(Keyword::Placement),
            "component" => Some(Keyword::Component),
            "place" => Some(Keyword::Place),
            "library" => Some(Keyword::Library),
            "image" => Some(Keyword::Image),
            "pin" => Some(Keyword::Pin),
            "padstack" => Some(Keyword::Padstack),
            "shape" => Some(Keyword::Shape),
            "circle" => Some(Keyword::Circle),
            "rect" | "rectangle" => Some(Keyword::Rectangle),
            "polygon" => Some(Keyword::Polygon),
            "path" => Some(Keyword::Path),
            "network" => Some(Keyword::Network),
            "net" => Some(Keyword::Net),
            "pins" => Some(Keyword::Pins),
            "class" => Some(Keyword::Class),
            "classes" => Some(Keyword::Classes),
            "wiring" => Some(Keyword::Wiring),
            "wire" => Some(Keyword::Wire),
            "via_rule" => Some(Keyword::ViaRule),
            "session" => Some(Keyword::Session),
            "routes" => Some(Keyword::Routes),
            "plane" => Some(Keyword::Plane),
            "autoroute" => Some(Keyword::Autoroute),
            "fanout" => Some(Keyword::Fanout),
            "postroute" => Some(Keyword::Postroute),
            "host_cad" | "hostcad" => Some(Keyword::HostCad),
            "host_version" | "hostversion" => Some(Keyword::HostVersion),
            "supply_pin" => Some(Keyword::SupplyPin),
            _ => None,
        }
    }
}
